In [1]:
import numpy as np

## Creación y Indexación:

1. Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

In [4]:
array1 = np.random.randint(10,100,50)
print(array1)
print(array1[::5])

[80 37 36 90 94 34 17 69 22 62 26 97 62 53 90 19 28 62 72 61 72 27 56 74
 56 79 49 74 27 81 12 79 94 93 90 50 28 31 78 52 91 80 49 80 89 28 32 35
 22 26]
[80 34 26 19 72 79 12 50 91 28]


2. Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [50]:
array2 = np.random.randint(1,21,30)
print(array2)
print(array2[1::2])

[ 8  3  3  9  1  6 19 16 12  6  9  8 12  1 19 10 20  9  3 15 14 16  1 11
 15 16  8  5  2  4]
[ 3  9  6 16  6  8  1 10  9 15 16 11 16  5  4]


3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [55]:
array3 = np.random.rand(4,6)*5
print(array3)

[[1.74211521 4.5081026  4.12862119 2.18082736 0.28159872 2.34573613]
 [4.42314413 1.17578674 2.41390195 2.03063115 1.24166328 1.61082028]
 [0.02957012 3.3326964  3.85051036 0.92560244 0.2677019  2.24838414]
 [1.92198056 1.13033517 0.84508271 3.29538818 4.01847033 1.53578308]]


In [57]:
array3 = np.random.random_sample((4,6))*5
print(array3)
print(np.round(array3[-1],2))

[[2.92804906 3.71605051 0.28577533 1.07634172 3.00150146 0.56939215]
 [2.19460522 1.06322384 1.63293694 2.61027609 3.3418496  3.60768684]
 [0.60001396 1.01629941 0.71030214 2.2148145  1.83639431 3.21751273]
 [0.58049009 4.68183997 4.22386996 0.17385018 4.94810327 0.13240812]]
[0.58 4.68 4.22 0.17 4.95 0.13]



BONUS: Crea un array 3D de forma (2, 3, 5) y 30 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

In [113]:
array4 = np.random.randint(0,101,(2,3,5))
print(array4)

[[[44  9 28  9 97]
  [56 15 28 10 57]
  [16 48 73 35  5]]

 [[75  5 61 53 24]
  [ 1 34 92 50 33]
  [58 78 27 64 40]]]


In [114]:
array5 = array4.flatten()
# array6 = array5[::3] = 0
array5[2::3] = 0
array5

array([44,  9,  0,  9, 97,  0, 15, 28,  0, 57, 16,  0, 73, 35,  0, 75,  5,
        0, 53, 24,  0, 34, 92,  0, 33, 58,  0, 27, 64,  0])

In [115]:
array5.reshape(2,3,5)

array([[[44,  9,  0,  9, 97],
        [ 0, 15, 28,  0, 57],
        [16,  0, 73, 35,  0]],

       [[75,  5,  0, 53, 24],
        [ 0, 34, 92,  0, 33],
        [58,  0, 27, 64,  0]]])

## Reshape y Transpose:
### Ejercicios con reshape:

1. Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

2. Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 61 (sin incluir). Utiliza reshape para convertirlo en un array 2D.



In [61]:
array = np.random.randint(1,101,(2,3,4))
print(array)
print(np.reshape(array,(4,6)))

[[[41 67 96 22]
  [44 26 12 23]
  [74  3 21 58]]

 [[24 83  9 13]
  [54 57 83 49]
  [ 7 47  1 20]]]
[[41 67 96 22 44 26]
 [12 23 74  3 21 58]
 [24 83  9 13 54 57]
 [83 49  7 47  1 20]]


In [63]:
array1 = np.random.randint(1,61,(3,4,5))
print(array1)

print(np.reshape(array1,(6,10)))

[[[37 30 56 12 38]
  [42 24 18 55  4]
  [ 2 56 28 39 37]
  [30 58 33 47 22]]

 [[17 44 38  9 49]
  [32 12 49 34 49]
  [12 56 18 16 39]
  [18 52 48 29 59]]

 [[23 14 16  3 31]
  [48 45 45 46 44]
  [56  7 24 25 42]
  [43 49  4 44 60]]]
[[37 30 56 12 38 42 24 18 55  4]
 [ 2 56 28 39 37 30 58 33 47 22]
 [17 44 38  9 49 32 12 49 34 49]
 [12 56 18 16 39 18 52 48 29 59]
 [23 14 16  3 31 48 45 45 46 44]
 [56  7 24 25 42 43 49  4 44 60]]


### Ejercicios con transpose:

3. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).

In [66]:
np.transpose(array1,(2,1,0))

array([[[37, 17, 23],
        [42, 32, 48],
        [ 2, 12, 56],
        [30, 18, 43]],

       [[30, 44, 14],
        [24, 12, 45],
        [56, 56,  7],
        [58, 52, 49]],

       [[56, 38, 16],
        [18, 49, 45],
        [28, 18, 24],
        [33, 48,  4]],

       [[12,  9,  3],
        [55, 34, 46],
        [39, 16, 25],
        [47, 29, 44]],

       [[38, 49, 31],
        [ 4, 49, 44],
        [37, 39, 42],
        [22, 59, 60]]])

4. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 5, 4).

In [67]:
array1

array([[[37, 30, 56, 12, 38],
        [42, 24, 18, 55,  4],
        [ 2, 56, 28, 39, 37],
        [30, 58, 33, 47, 22]],

       [[17, 44, 38,  9, 49],
        [32, 12, 49, 34, 49],
        [12, 56, 18, 16, 39],
        [18, 52, 48, 29, 59]],

       [[23, 14, 16,  3, 31],
        [48, 45, 45, 46, 44],
        [56,  7, 24, 25, 42],
        [43, 49,  4, 44, 60]]])

In [68]:
np.transpose(array1,(0,2,1))

array([[[37, 42,  2, 30],
        [30, 24, 56, 58],
        [56, 18, 28, 33],
        [12, 55, 39, 47],
        [38,  4, 37, 22]],

       [[17, 32, 12, 18],
        [44, 12, 56, 52],
        [38, 49, 18, 48],
        [ 9, 34, 16, 29],
        [49, 49, 39, 59]],

       [[23, 48, 56, 43],
        [14, 45,  7, 49],
        [16, 45, 24,  4],
        [ 3, 46, 25, 44],
        [31, 44, 42, 60]]])

### Preguntas teóricas:

5. ¿Qué diferencia existe entre el reshape y el transpose?
5.1. reshape - Cambia la forma sin cambiar los datos
5.2. transpose - intercambia las dimensiones sin cambiar los datos

6. ¿Y entre el transpose y el swapaxes?
6.1. transpose - intercambia las dimensiones sin cambiar los datos.
6.2. swapaxes - cambia dos ejes de un array.

## Funciones Aritméticas y Estadísticas:

1. Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

In [4]:
array = np.round(np.random.rand(2,3,5),1)
array

array([[[0.1, 0.3, 0.8, 0.3, 0.8],
        [0.4, 0.5, 0.5, 0.1, 0.8],
        [0.3, 0.9, 0.3, 0.3, 0.4]],

       [[0.8, 0.7, 0.5, 0.9, 0.1],
        [0.5, 0.2, 0.9, 0.1, 0.7],
        [0.9, 0.6, 0.2, 0.1, 0.3]]])

2. Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

    2.1. Si el valor del array es igual que la media, se reemplaza por "A".

    2.2. Si el valor del array es mayor que la media, se reemplaza por "B".

    2.3. Si el valor del array es menor que la media, se reemplaza por "C".

    2.4. Si el valor es igual que el máximo, se reemplaza por "D".

    2.5. Si el valor es igual que el mínimo, se reemplaza por "E".

In [5]:
array_vacio = np.empty((2,3,5))
array_vacio

array([[[0.1, 0.3, 0.8, 0.3, 0.8],
        [0.4, 0.5, 0.5, 0.1, 0.8],
        [0.3, 0.9, 0.3, 0.3, 0.4]],

       [[0.8, 0.7, 0.5, 0.9, 0.1],
        [0.5, 0.2, 0.9, 0.1, 0.7],
        [0.9, 0.6, 0.2, 0.1, 0.3]]])

In [6]:
media = np.round(np.mean(array),1)
media

0.5

In [7]:
array

array([[[0.1, 0.3, 0.8, 0.3, 0.8],
        [0.4, 0.5, 0.5, 0.1, 0.8],
        [0.3, 0.9, 0.3, 0.3, 0.4]],

       [[0.8, 0.7, 0.5, 0.9, 0.1],
        [0.5, 0.2, 0.9, 0.1, 0.7],
        [0.9, 0.6, 0.2, 0.1, 0.3]]])

In [8]:
array_final = np.where(array == media, "A", np.where(np.min(array) == array, "E", np.where(array < media, "C", np.where(np.max(array) == array, "D", np.where(array > media, "B", "x")))))
array_final

array([[['E', 'C', 'B', 'C', 'B'],
        ['C', 'A', 'A', 'E', 'B'],
        ['C', 'D', 'C', 'C', 'C']],

       [['B', 'B', 'A', 'D', 'E'],
        ['A', 'C', 'D', 'E', 'B'],
        ['D', 'B', 'C', 'E', 'C']]], dtype='<U1')

In [11]:
flat_array = array.flatten()
list(flat_array)

[0.1,
 0.3,
 0.8,
 0.3,
 0.8,
 0.4,
 0.5,
 0.5,
 0.1,
 0.8,
 0.3,
 0.9,
 0.3,
 0.3,
 0.4,
 0.8,
 0.7,
 0.5,
 0.9,
 0.1,
 0.5,
 0.2,
 0.9,
 0.1,
 0.7,
 0.9,
 0.6,
 0.2,
 0.1,
 0.3]